config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount AvatarUserImageUploader.upload_endpoint(:cache) => '/images/upload'

  authenticate :user, ->(u) { Rails.env.development? && u.admin? } do
    require 'sidekiq/web'

    mount Sidekiq::Web, at: '/sidekiq'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    # Profile user routes
    authenticated :user, ->(u) { u.profile? } do
      root 'profiles#show', as: :profile_root

      resource :profile, except: %i[index create new destroy] do
        get :change_password, on: :collection
        put :update_password, on: :collection
        get :destroy, on: :collection, as: :delete
      end
    end

    # Admin user routes
    authenticated :user, ->(u) { u.admin? } do
      root to: 'admin/dashboard#index', as: :admin_root

      namespace :admin do
        resources :users do
          put :up, on: :member
          put :down, on: :member
          get :upload, on: :collection
          post :import, on: :collection
        end
      end
    end

    delete 'logout', to: 'sessions#destroy'
  end

  # Guest routes
  unauthenticated :auth do
    root 'guest#index'
    post 'login', to: 'sessions#create'
    get 'register', to: 'registrations#new'
    post 'registration', to: 'registrations#create'
    get 'create_password', to: 'registrations#create_password', as: :guest_create_password
    post 'update_password', to: 'registrations#update_password', as: :guest_update_password
  end
end

app/models/user.rb
# frozen_string_literal: true

# This class represents an user in the application. It provides features such as
# authentication, authorization, user profile creation and storage of information.
class User < ApplicationRecord
  devise :database_authenticatable

  include AvatarUserImageUploader::Attachment(:avatar_image)
  enum role: { profile: 0, admin: 1 }

  validates :fullname, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  # Controller for managing users.
  class UsersController < AdminController
    before_action :authenticate_user!
    before_action :find_user, only: %i[show edit update destroy up down]

    def index
      @users = AdminContext::UserDecorator.wrap(User.all, current_user)
    end

    def show
      @user = AdminContext::UserDecorator.new(User.find(params[:id]), current_user)
    end

    def new
      @presenter = presenter_class.new(
        view_context, current_user, form_object: AdminContext::CreateUserForm.new
      )
    end

    def edit
      @presenter = presenter_class.new(
        view_context,
        current_user,
        form_object: AdminContext::EditUserForm.new(user: @user)
      )
    end

    def create
      form = AdminContext::CreateUserForm.new(user_params)

      if form.submit(current_user.id)
        redirect_to admin_user_path(form.user.id), notice: t('.success')
      else
        @presenter = presenter_class.new(view_context, current_user, form_object: form)
        render :new
      end
    end

    def update
      form = AdminContext::EditUserForm.new(user_params)

      if form.submit(current_user.id, @user.id)
        redirect_to admin_user_path(@user.id), notice: t('.success')
      else
        @presenter = presenter_class.new(view_context, current_user, form_object: form)
        render :edit
      end
    end

    def destroy
      result = AdminContext::DeleteUserOperation.call(current_user.id, @user.id)

      if result.success?
        redirect_to admin_users_path, notice: t('.success')
      else
        redirect_to edit_admin_user_path(@user.id), alert: t('.error')
      end
    end

    def up
      result = AdminContext::UserUpOperation.call(current_user.id, @user.id)

      if result.success?
        redirect_to request.referer, notice: t('.success', fullname: @user.fullname)
      else
        redirect_to edit_admin_user_path(@user.id), alert: t('.error', fullname: @user.fullname)
      end
    end

    def down
      result = AdminContext::UserDownOperation.call(current_user.id, @user.id)

      if result.success?
        redirect_to request.referer, notice: t('.success', fullname: @user.fullname)
      else
        redirect_to edit_admin_user_path(@user.id), alert: t('.error', fullname: @user.fullname)
      end
    end

    def upload
      @presenter = presenter_class.new(
        view_context,
        current_user,
        form_object: AdminContext::ImportSpreadsheetForm.new
      )
    end

    def import
      form = AdminContext::ImportSpreadsheetForm.new(import_params)

      if form.submit(current_user.id)
        redirect_to admin_users_path, notice: t('.success', total: form.counter)
      else
        @presenter = presenter_class.new(view_context, current_user, form_object: form)
        render :upload
      end
    end

    private

    def presenter_class
      AdminContext::UserPresenter
    end

    def user_params
      params.require(:user).permit(:fullname, :email, :avatar_image)
    end

    def find_user
      @user = User.find(params[:id])
    end

    def import_params
      params.require(:import).permit(:file)
    end
  end
end

app/views/admin/users/edit.html.erb
<div class="row-fluid">
  <%= @presenter.render_edit_user_form %>
</div>

app/views/admin/users/index.html.erb
<table id="admin-users-table" class="table mb-3">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= I18n.t('activerecord.attributes.user.fullname') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.user.email') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.user.role') %></th>
      <th scope="col"><%= I18n.t('views.admin.users.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <%= render partial: 'shared/admin/users/row', locals: { user: user } %>
    <% end %>
  </tbody>
</table>

<%= link_to I18n.t('views.admin.users.index.add'), new_admin_user_path, class: "btn btn-outline-primary" %>
<%= link_to I18n.t('views.admin.users.index.import'), upload_admin_users_path, class: "btn btn-outline-success" %>

app/views/admin/users/new.html.erb
<div class="row-fluid">
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong><%= I18n.t('views.admin.users.heads_up') %>!</strong>
    <%= I18n.t('views.admin.users.new.message') %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

  <%= @presenter.render_new_user_form %>
</div>

app/views/admin/users/show.html.erb
<div class="row-fluid">
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0"><%= I18n.t('activerecord.attributes.user.avatar_image') %></p>
        </div>
        <div class="col-sm-9">
          <%= @user.image_tag_avatar(:small) %>
        </div>
      </div>
      <hr />

      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0"><%= I18n.t('activerecord.attributes.user.fullname') %></p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @user.fullname %></p>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0"><%= I18n.t('activerecord.attributes.user.email') %></p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @user.email %></p>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0"><%= I18n.t('activerecord.attributes.user.role') %></p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">
            <%= @user.badge_role %>
          </p>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0"><%= I18n.t('views.admin.users.actions') %></p>
        </div>
        <div class="col-sm-9">
          <%= @user.link_to_edit %>
          <%= @user.link_to_convert %>
          <%= @user.link_to_delete %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/upload.html.erb
<div class="row-fluid">
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong><%= I18n.t('views.admin.users.heads_up') %>!</strong>
    <%= I18n.t('views.admin.users.upload.message') %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

  <%= @presenter.render_upload_spreadsheet_form %>
</div>