config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount AvatarUserImageUploader.upload_endpoint(:cache) => '/images/upload'

  authenticate :user, ->(u) { Rails.env.development? && u.admin? } do
    require 'sidekiq/web'

    mount Sidekiq::Web, at: '/sidekiq'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    # Profile user routes
    authenticated :user, ->(u) { u.profile? } do
      root 'profiles#show', as: :profile_root

      resource :profile, except: %i[index create new destroy] do
        get :change_password, on: :collection
        put :update_password, on: :collection
        get :destroy, on: :collection, as: :delete
      end
    end

    # Admin user routes
    authenticated :user, ->(u) { u.admin? } do
      root to: 'admin/dashboard#index', as: :admin_root

      namespace :admin do
        resources :users do
          put :up, on: :member
          put :down, on: :member
          get :upload, on: :collection
          post :import, on: :collection
        end
      end
    end

    delete 'logout', to: 'sessions#destroy'
  end

  # Guest routes
  unauthenticated :auth do
    root 'guest#index'
    post 'login', to: 'sessions#create'
    get 'register', to: 'registrations#new'
    post 'registration', to: 'registrations#create'
    get 'create_password', to: 'registrations#create_password', as: :guest_create_password
    post 'update_password', to: 'registrations#update_password', as: :guest_update_password
  end
end

app/views/shared/admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to current_user.fullname, profile_root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<%= admin_users_path %>">
            <%= I18n.t('views.shared.admin.users.navbar.list_users') %>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav d-flex">
        <li class="nav-item">
         <%= link_to I18n.t('views.shared.admin.users.navbar.sign_out'), logout_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/admin/_toast.html.erb
<div class="toast-container position-fixed top-0 end-0 p-3">
  <div id="admin-live-toast" class="toast" role="alert" aria-live="assertive" aria-atomic="true"  data-bs-delay="5000">
    <div class="toast-header">
      <strong class="me-auto">New Event</strong>
      <small>now</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div id="admin-live-toast-boby" class="toast-body"></div>
  </div>
</div>