config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount AvatarUserImageUploader.upload_endpoint(:cache) => '/images/upload'

  authenticate :user, ->(u) { Rails.env.development? && u.admin? } do
    require 'sidekiq/web'

    mount Sidekiq::Web, at: '/sidekiq'
  end

  devise_for :users, skip: :all
  devise_scope :user do
    # Profile user routes
    authenticated :user, ->(u) { u.profile? } do
      root 'profiles#show', as: :profile_root

      resource :profile, except: %i[index create new destroy] do
        get :change_password, on: :collection
        put :update_password, on: :collection
        get :destroy, on: :collection, as: :delete
      end
    end

    # Admin user routes
    authenticated :user, ->(u) { u.admin? } do
      root to: 'admin/dashboard#index', as: :admin_root

      namespace :admin do
        resources :users do
          put :up, on: :member
          put :down, on: :member
          get :upload, on: :collection
          post :import, on: :collection
        end
      end
    end

    delete 'logout', to: 'sessions#destroy'
  end

  # Guest routes
  unauthenticated :auth do
    root 'guest#index'
    post 'login', to: 'sessions#create'
    get 'register', to: 'registrations#new'
    post 'registration', to: 'registrations#create'
    get 'create_password', to: 'registrations#create_password', as: :guest_create_password
    post 'update_password', to: 'registrations#update_password', as: :guest_update_password
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

# This class provides methods for user manage your profile.
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  layout 'profile'

  def show
    @user = ProfileContext::UserDecorator.new(current_user)
  end

  def edit
    attributes = current_user.attributes.slice('fullname', 'email')

    @user = ProfileContext::UserDecorator.new(current_user)
    @presenter = presenter_class.new(
      view_context, current_user, form_object: profile_fields_form.new(attributes)
    )
  end

  def update
    form = profile_fields_form.new(profile_fields_params)

    if form.submit(current_user.id)
      redirect_to profile_root_path, notice: t('.success')
    else
      @user = ProfileContext::UserDecorator.new(current_user)
      @presenter = presenter_class.new(view_context, current_user, form_object: form)

      render :edit
    end
  end

  def destroy
    result = ProfileContext::DeleteProfileOperation.call(current_user.id)

    if result.success?
      redirect_to root_path, notice: t('.success')
    else
      redirect_to profile_root_path, alert: t('.error')
    end
  end

  def change_password
    @user = ProfileContext::UserDecorator.new(current_user)
    @presenter = presenter_class.new(view_context, current_user, form_object: update_password_form.new)
  end

  def update_password
    form = update_password_form.new(update_password_params)

    if form.submit(current_user.id)
      redirect_to profile_root_path, notice: t('.success')
    else
      @user = ProfileContext::UserDecorator.new(current_user)
      @presenter = presenter_class.new(view_context, current_user, form_object: form)

      render :change_password
    end
  end

  private

  def presenter_class
    ProfileContextPresenter
  end

  def update_password_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end

  def update_password_form
    ProfileContext::UpdatePasswordForm
  end

  def profile_fields_params
    params.require(:user).permit(:fullname, :email, :avatar_image)
  end

  def profile_fields_form
    ProfileContext::UpdateFieldsForm
  end
end

app/views/shared/profile/_change_password_form.html.erb
<%= simple_form_for(form_object, method: :put, url: update_password_profile_path, html: { id: 'profile-update-password-form' }) do |f| %>

  <% if f.object.errors[:base].present? %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence %>
  <% end %>

  <%= f.input :current_password, label: false, input_html: { value: f.object.current_password } %>
  <%= f.input :password, label: false, input_html: { value: f.object.password } %>
  <%= f.input :password_confirmation, label: false, input_html: { value: f.object.password_confirmation } %>
  <%= f.button :submit, I18n.t('simple_form.buttons.submit'), class: 'w-100 btn btn-primary btn-block mb-4' %>
<% end %>

app/views/shared/profile/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= @user.image_tag_avatar(:tiny) %>
    <%= link_to @user.fullname, profile_root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<%= edit_profile_path %>">
            <%= I18n.t('views.profile.edit_profile') %>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="<%= change_password_profile_path %>">
            <%= I18n.t('views.profile.change_password') %>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav d-flex">
        <li class="nav-item">
         <%= link_to I18n.t('views.profile.delete_profile'), delete_profile_path, id: 'navbar-profile-btn-delete', class: 'nav-link', data: { confirm: 'Are you sure? This action is irreversible' } %>
        </li>
        <li class="nav-item">
         <%= link_to I18n.t('views.shared.profile.navbar.sign_out'), logout_path, id: 'navbar-profile-btn-logout', method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/profile/_toast.html.erb
<div class="toast-container position-fixed top-0 end-0 p-3">
  <div id="profile-live-toast" class="toast" role="alert" aria-live="assertive" aria-atomic="true"  data-bs-delay="5000">
    <div class="toast-header">
      <strong class="me-auto">New Event</strong>
      <small>now</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div id="profile-live-toast-boby" class="toast-body"></div>
  </div>
</div>

app/views/shared/profile/_update_fields_form.html.erb
<%= simple_form_for(form_object, method: :put, url: profile_path, html: { id: 'profile-update-form', class: 'with-avatar-upload' }) do |f| %>
  <% if f.object.errors[:base].present? %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence %>
  <% end %>

  <%= f.input :fullname, label: false %>
  <%= f.input :email, label: false %>
  <%= f.input :avatar_image, as: :file, label: false, input_html: { id: 'user_avatar_image', accept: 'image/png, image/jpeg, image/jpg' } %>
  <%= f.input :avatar_image, as: :hidden, input_html: { id: 'user_avatar_image_hidden', value: {} } %>
  <%= render 'shared/global/progress_bar' %>

  <%= f.button :submit, I18n.t('simple_form.buttons.submit'), class: 'w-100 btn btn-primary btn-block mb-4' %>
<% end %>